services:
    django:
        build:
            context: .
        container_name: django
        volumes:
            -   ./:/app
        working_dir: /app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
